cat stream_tmpl.tmpl | sed s/XXX/Between/g | sed s/xxx/between/g > stream_between.go
cat stream_tmpl.tmpl | sed s/XXX/Bottom/g | sed s/xxx/bottom/g > stream_bottom.go
cat stream_tmpl.tmpl | sed s/XXX/Ceil/g | sed s/xxx/ceil/g > stream_ceil.go
cat stream_tmpl.tmpl | sed s/XXX/Delta/g | sed s/xxx/delta/g > stream_delta.go
cat stream_tmpl.tmpl | sed s/XXX/Dimensions/g | sed s/xxx/dimensions/g > stream_dimensions.go
cat stream_tmpl.tmpl | sed s/XXX/DoubleEWMA/g | sed s/xxx/doubleEWMA/g > stream_doubleewma.go
cat stream_tmpl.tmpl | sed s/XXX/Equals/g | sed s/xxx/equals/g > stream_equals.go
cat stream_tmpl.tmpl | sed s/XXX/EWMA/g | sed s/xxx/eWMA/g > stream_ewma.go
cat stream_tmpl.tmpl | sed s/XXX/Floor/g | sed s/xxx/floor/g > stream_floor.go
cat stream_tmpl.tmpl | sed s/XXX/HistogramPercentile/g | sed s/xxx/histogramPercentile/g > stream_histogrampercentile.go
cat stream_tmpl.tmpl | sed s/XXX/Integrate/g | sed s/xxx/integrate/g > stream_integrate.go
cat stream_tmpl.tmpl | sed s/XXX/Log10/g | sed s/xxx/log10/g > stream_log10.go
cat stream_tmpl.tmpl | sed s/XXX/Log/g | sed s/xxx/log/g > stream_log.go
cat stream_tmpl.tmpl | sed s/XXX/Map/g | sed s/xxx/map/g > stream_map.go
cat stream_tmpl.tmpl | sed s/XXX/MeanPlusStdDev/g | sed s/xxx/meanPlusStdDev/g > stream_meanplusstddev.go
cat stream_tmpl.tmpl | sed s/XXX/NotEquals/g | sed s/xxx/notEquals/g > stream_notequals.go
cat stream_tmpl.tmpl | sed s/XXX/Pow/g | sed s/xxx/pow/g > stream_pow.go
cat stream_tmpl.tmpl | sed s/XXX/Promote/g | sed s/xxx/promote/g > stream_promote.go
cat stream_tmpl.tmpl | sed s/XXX/RateofChange/g | sed s/xxx/rateofChange/g > stream_rateofchange.go
cat stream_tmpl.tmpl | sed s/XXX/Sqrt/g | sed s/xxx/sqrt/g > stream_sqrt.go
cat stream_tmpl.tmpl | sed s/XXX/StdDev/g | sed s/xxx/stdDev/g > stream_stddev.go
